dist: xenial
sudo: true
language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - python3
      - doxygen
      - graphviz
      - libgtkmm-3.0-dev
      - libxi-dev
      - libx11-dev

script:
  - export CXX=/usr/bin/g++
  - export CC=/usr/bin/gcc
  - ./scripts/install_stmm-input-all.py  -b=Debug -s=Off -d=Off -t=On

